name: ArchiEvent
version: '${project.version}'
main: fr.archipel.archiEvent.ArchiEvent
api-version: '1.21'
softdepend: [WorldEdit, FastAsyncWorldEdit]

commands:
  archievent:
    description: Commande principale ArchiEvent
    usage: /archievent <commande>
    aliases: [event]

permissions:
  archievent.staff:
    description: Accès aux commandes staff ArchiEvent
    default: op